### ISSUE TITLE
[Symbol] Implement missing transaction forms

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-desktop-wallet#917]
**Components:** 
- [x] `src/views/forms/FormTransferTransaction`
- [ ] `src/views/forms/FormAliasTransaction`
- [x] `src/views/forms/FormMosaicDefinitionTransaction`
- [x] `src/views/forms/FormNamespaceRegistrationTransaction`
- [x] `src/views/forms/FormMultisigAccountModificationTransaction`

**Task description:**
All transaction forms **should use `TransactionFormBase`** abstract class as their base component class (extending TransactionFormBase instead of Vue)
