### ISSUE TITLE
[Symbol] TransactionConfirmation/TransactionDetails with TransactionView

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-desktop-wallet#923]
**Components:** 
- [x] `src/components/TransactionDetails/BaseTransactionDetails`
- [x] `src/components/TransactionDetails/TransferTransaction`
- [x] `src/components/TransactionDetails/MosaicDefinitionTransaction`
- [x] `src/components/TransactionDetails/NamespaceRegistrationTransaction`
- [x] `src/components/TransactionDetails/CustomTransaction` (used for types "not yet specialized")

**Task description:**
All transaction details component should make use of `TransactionDetails/TransactionDetails` as a base component in order to avoid code duplication for this part of the software.

Specialized transaction details components should define and render a simple list of fields formatted in order to improve readability of a transaction's details.

**Comment by evias** [comment]
merged in `v2-alpha` with https://github.com/nemfoundation/nem2-desktop-wallet/commit/4f3f7cc750240798c43eb66b20f14bc2ac08af1c
